### ISSUE TITLE
The css isn't loading on localhost 

### ISSUE THREAD

**Issue by Temian1** [abourtnik/clip-zone#1]
I tired working on it on localhost but the css and js are not rendering what could have happened

**Comment by abourtnik** [comment]
Hello @Temian1, for start project you need to execute `make start` command

**Comment by Temian1** [comment]
> Hello @Temian1, for start project you need to execute `make start` command

You mean 'php artisan start' , because I did that, I can't run "npm build" also I get error anytime I do that

**Comment by abourtnik** [comment]
No `make start` this command run followings commands :

```
docker-compose up -d
docker exec -it php_container npm run dev
```

https://github.com/abourtnik/clip-zone/blob/f40328525b851eeb259970dd06e3e3f95672ec86/Makefile#L13

You can run this command manually if you want
