### ISSUE TITLE
this is a feature request

### ISSUE THREAD

**Issue by Temian1** [abourtnik/clip-zone#2]
is there a feature to allow us to embed other platforms ,like youtube and tiktok , facebook

**Comment by abourtnik** [comment]
Hello @Temian1,  I'm not sure to understand, you want to import videos from other social plateforms ? Or you want to embed a ClipZone video in iframe on your website like this : 
![Capture d’écran 2023-09-07 à 19 56 55](https://github.com/abourtnik/clip-zone/assets/23094492/e276b9c6-5cc8-4fea-b791-5fc23337b265) ?

**Comment by Temian1** [comment]
Yes like that , embedding videos from other platform will be a good feature in my case , it will also save a lot of storage

**Comment by abourtnik** [comment]
Hello @Temian1 the feature is on production, you can try and tell me if this work good 😄


![Capture d’écran 2023-09-12 à 23 52 52](https://github.com/abourtnik/clip-zone/assets/23094492/f21ecb99-d2bf-488e-8abe-6c8c760b3810)
![Capture d’écran 2023-09-12 à 23 52 42](https://github.com/abourtnik/clip-zone/assets/23094492/7fd548eb-be95-4437-bdf7-7e942d551c14)
